app = 'tetris-atlas'
primary_region = 'ord'

[build]
dockerfile = ".docker/Dockerfile.run"

[env]
PORT = '8080'

[[vm]]
memory = '32gb'
cpu_kind = 'performance'
cpus = 4
gpu_kind = "l40s"
gpus = 1

[[mounts]]
source = "data"
destination = "/data"
processes = ["app"]
